#!/bin/bash
if [ ! -d "/sys/class/gpio/gpio26" ]; then
    echo "26" > /sys/class/gpio/export
fi
echo "out" > /sys/class/gpio/gpio26/direction
echo "1" > /sys/class/gpio/gpio26/value
sleep 1
echo "0" > /sys/class/gpio/gpio26/value
